# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 420)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("   background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0,\n"
"    stop:0 rgba(81, 0, 135, 255),\n"
"    stop:0.427447 rgba(41, 61, 132, 235),\n"
"    stop:1 rgba(155, 79, 165, 255));\n"
"font-family: Noto Sans SC;")
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input_image = QtWidgets.QLabel(self.centralwidget)
        self.input_image.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.input_image.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_image.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"border:1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;")
        self.input_image.setAlignment(QtCore.Qt.AlignCenter)
        self.input_image.setObjectName("input_image")
        self.horizontalLayout.addWidget(self.input_image)
        self.image2 = QtWidgets.QLabel(self.centralwidget)
        self.image2.setMouseTracking(False)
        self.image2.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"border:1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;")
        self.image2.setAlignment(QtCore.Qt.AlignCenter)
        self.image2.setWordWrap(False)
        self.image2.setObjectName("image2")
        self.horizontalLayout.addWidget(self.image2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Model_choose_button = QtWidgets.QPushButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\icons/smart_toy_42dp_E8EAED_FILL0_wght400_GRAD0_opsz40.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Model_choose_button.setIcon(icon)
        self.Model_choose_button.setObjectName("Model_choose_button")
        self.horizontalLayout_2.addWidget(self.Model_choose_button)
        self.Crop_button = QtWidgets.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\icons/crop_rotate_42dp_E8EAED_FILL0_wght400_GRAD0_opsz40.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Crop_button.setIcon(icon1)
        self.Crop_button.setObjectName("Crop_button")
        self.horizontalLayout_2.addWidget(self.Crop_button)
        self.Generator_button = QtWidgets.QPushButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\icons/token_42dp_E8EAED_FILL0_wght400_GRAD0_opsz40.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Generator_button.setIcon(icon2)
        self.Generator_button.setObjectName("Generator_button")
        self.horizontalLayout_2.addWidget(self.Generator_button)
        self.Learn_button = QtWidgets.QPushButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\icons/autorenew_42dp_E8EAED_FILL0_wght400_GRAD0_opsz40.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Learn_button.setIcon(icon3)
        self.Learn_button.setObjectName("Learn_button")
        self.horizontalLayout_2.addWidget(self.Learn_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Start_button = QtWidgets.QPushButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\icons/task_alt_42dp_E8EAED_FILL0_wght400_GRAD0_opsz40.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Start_button.setIcon(icon4)
        self.Start_button.setObjectName("Start_button")
        self.horizontalLayout_3.addWidget(self.Start_button)
        self.Test_button = QtWidgets.QPushButton(self.centralwidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(".\\icons/empty_dashboard_42dp_E8EAED_FILL0_wght400_GRAD0_opsz40.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Test_button.setIcon(icon5)
        self.Test_button.setObjectName("Test_button")
        self.horizontalLayout_3.addWidget(self.Test_button)
        self.Save_button = QtWidgets.QPushButton(self.centralwidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(".\\icons/save_42dp_E8EAED_FILL0_wght400_GRAD0_opsz40.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Save_button.setIcon(icon6)
        self.Save_button.setObjectName("Save_button")
        self.horizontalLayout_3.addWidget(self.Save_button)
        self.Clear_button = QtWidgets.QPushButton(self.centralwidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(".\\icons/delete_42dp_E8EAED_FILL0_wght400_GRAD0_opsz40.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Clear_button.setIcon(icon7)
        self.Clear_button.setObjectName("Clear_button")
        self.horizontalLayout_3.addWidget(self.Clear_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.analyz = QtWidgets.QLabel(self.centralwidget)
        self.analyz.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"border:1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;")
        self.analyz.setText("")
        self.analyz.setAlignment(QtCore.Qt.AlignCenter)
        self.analyz.setObjectName("analyz")
        self.verticalLayout_2.addWidget(self.analyz)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "關防圖章AI辨識"))
        self.input_image.setText(_translate("MainWindow", "印章圖像"))
        self.image2.setText(_translate("MainWindow", "模型印章"))
        self.Model_choose_button.setText(_translate("MainWindow", "選擇模型"))
        self.Crop_button.setText(_translate("MainWindow", "準備印章"))
        self.Generator_button.setText(_translate("MainWindow", "生成機"))
        self.Learn_button.setText(_translate("MainWindow", "教育 "))
        self.Start_button.setText(_translate("MainWindow", "開始"))
        self.Test_button.setText(_translate("MainWindow", "測試模型"))
        self.Save_button.setText(_translate("MainWindow", "保存"))
        self.Clear_button.setText(_translate("MainWindow", "清除"))
